### ISSUE TITLE
Is is possible to implement a simple ssh client using tclmtls?

### ISSUE THREAD

**Issue by misha-franz** [chpock/tclmtls#5]
Apology, my security knowledge is quite basic.  I wrote a Tcl/Tk app which wraps plink and pscp from putty package and adds some UI...  I am thinking to maybe eventually re-write it without the need of 3rd party apps.

**Comment by chpock** [comment]
The SSH protocol is different from the TLS protocol, so this is not possible.

I don't think the SSH implementation exists in Tcl. The best solution is to use command line utilities as you mentioned and control them via pipes/command line options.
